-- Radar Estratégico Empresarial
-- Controle real de acesso, aprovação e isolamento de leads.
-- Execute este arquivo no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null default '',
  phone text not null default '',
  professional_title text not null default '',
  role text not null default 'user' check (role in ('user','admin')),
  approval_status text not null default 'pending' check (approval_status in ('pending','approved','rejected','suspended')),
  requested_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id text primary key,
  owner_user_id uuid not null references auth.users(id) on delete restrict,
  company_name text not null default '',
  cnpj text not null default '',
  stage text not null default 'identificada',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_owner_user_id_idx on public.leads(owner_user_id);
create index if not exists leads_stage_idx on public.leads(stage);
create index if not exists profiles_approval_status_idx on public.profiles(approval_status);

create table if not exists public.access_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id),
  target_user_id uuid references auth.users(id),
  lead_id text,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists leads_touch_updated_at on public.leads;
create trigger leads_touch_updated_at
before update on public.leads
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    email,
    full_name,
    phone,
    professional_title,
    role,
    approval_status
  ) values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    coalesce(new.raw_user_meta_data->>'phone',''),
    coalesce(new.raw_user_meta_data->>'professional_title',''),
    'user',
    'pending'
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = case when public.profiles.full_name = '' then excluded.full_name else public.profiles.full_name end,
    phone = case when public.profiles.phone = '' then excluded.phone else public.profiles.phone end,
    professional_title = case when public.profiles.professional_title = '' then excluded.professional_title else public.profiles.professional_title end;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin(check_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = check_user
      and p.role = 'admin'
      and p.approval_status = 'approved'
  );
$$;

create or replace function public.is_approved(check_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = check_user
      and p.approval_status = 'approved'
  );
$$;

alter table public.profiles enable row level security;
alter table public.leads enable row level security;
alter table public.access_audit enable row level security;

drop policy if exists "profile owner or admin can read" on public.profiles;
create policy "profile owner or admin can read"
on public.profiles for select
to authenticated
using (auth.uid() = id or public.is_admin());

drop policy if exists "admin can update profiles" on public.profiles;
create policy "admin can update profiles"
on public.profiles for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "approved users read owned leads admin reads all" on public.leads;
create policy "approved users read owned leads admin reads all"
on public.leads for select
to authenticated
using (
  public.is_approved()
  and (owner_user_id = auth.uid() or public.is_admin())
);

drop policy if exists "approved users insert owned leads admin inserts any" on public.leads;
create policy "approved users insert owned leads admin inserts any"
on public.leads for insert
to authenticated
with check (
  public.is_approved()
  and (owner_user_id = auth.uid() or public.is_admin())
);

drop policy if exists "approved users update owned leads admin updates all" on public.leads;
create policy "approved users update owned leads admin updates all"
on public.leads for update
to authenticated
using (
  public.is_approved()
  and (owner_user_id = auth.uid() or public.is_admin())
)
with check (
  public.is_approved()
  and (owner_user_id = auth.uid() or public.is_admin())
);

drop policy if exists "approved users delete owned leads admin deletes all" on public.leads;
create policy "approved users delete owned leads admin deletes all"
on public.leads for delete
to authenticated
using (
  public.is_approved()
  and (owner_user_id = auth.uid() or public.is_admin())
);

drop policy if exists "admin reads audit" on public.access_audit;
create policy "admin reads audit"
on public.access_audit for select
to authenticated
using (public.is_admin());

drop policy if exists "approved users create audit" on public.access_audit;
create policy "approved users create audit"
on public.access_audit for insert
to authenticated
with check (public.is_approved() and actor_user_id = auth.uid());

create or replace function public.set_user_access(target_user uuid, new_status text)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_profile public.profiles;
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem alterar acessos.';
  end if;

  if new_status not in ('approved','rejected','suspended','pending') then
    raise exception 'Status inválido.';
  end if;

  update public.profiles
  set approval_status = new_status,
      approved_at = case when new_status = 'approved' then now() else approved_at end,
      approved_by = case when new_status = 'approved' then auth.uid() else approved_by end
  where id = target_user
  returning * into updated_profile;

  insert into public.access_audit(actor_user_id,target_user_id,action,details)
  values(auth.uid(),target_user,'access_' || new_status,jsonb_build_object('status',new_status));

  return updated_profile;
end;
$$;

create or replace function public.set_user_role(target_user uuid, new_role text)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_profile public.profiles;
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem alterar perfis.';
  end if;

  if new_role not in ('user','admin') then
    raise exception 'Perfil inválido.';
  end if;

  update public.profiles
  set role = new_role
  where id = target_user
  returning * into updated_profile;

  insert into public.access_audit(actor_user_id,target_user_id,action,details)
  values(auth.uid(),target_user,'role_changed',jsonb_build_object('role',new_role));

  return updated_profile;
end;
$$;

create or replace function public.assign_lead(target_lead text, target_owner uuid)
returns public.leads
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_lead public.leads;
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem reatribuir leads.';
  end if;

  if not exists (
    select 1 from public.profiles
    where id = target_owner and approval_status = 'approved'
  ) then
    raise exception 'O responsável precisa estar aprovado.';
  end if;

  update public.leads
  set owner_user_id = target_owner
  where id = target_lead
  returning * into updated_lead;

  insert into public.access_audit(actor_user_id,target_user_id,lead_id,action,details)
  values(auth.uid(),target_owner,target_lead,'lead_reassigned',jsonb_build_object('owner_user_id',target_owner));

  return updated_lead;
end;
$$;

grant execute on function public.set_user_access(uuid,text) to authenticated;
grant execute on function public.set_user_role(uuid,text) to authenticated;
grant execute on function public.assign_lead(text,uuid) to authenticated;

-- PRIMEIRO ADMINISTRADOR
-- 1. Solicite acesso pelo próprio sistema com seu e-mail.
-- 2. Depois execute UMA VEZ, trocando o e-mail abaixo:
--
-- update public.profiles
-- set role = 'admin', approval_status = 'approved', approved_at = now()
-- where email = 'SEU_EMAIL_AQUI';
--
-- A partir daí, as demais aprovações são feitas dentro do sistema.
